config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :modern_quotes
  resources :quotes
  resources :static_pages

  get 'home', to: 'static_pages#home'

  root 'static_pages#home'

end

app/models/modern_quote.rb
class ModernQuote < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/modern_quotes_controller.rb
class ModernQuotesController < ApplicationController
  before_action :set_modern_quote, only: [:show, :edit, :update, :destroy]

  # GET /modern_quotes
  # GET /modern_quotes.json
  def index
    @modern_quotes = ModernQuote.all
  end

  # GET /modern_quotes/1
  # GET /modern_quotes/1.json
  def show
  end

  # GET /modern_quotes/new
  def new
    @modern_quote = ModernQuote.new
  end

  # GET /modern_quotes/1/edit
  def edit
  end

  # POST /modern_quotes
  # POST /modern_quotes.json
  def create
    @modern_quote = ModernQuote.new(modern_quote_params)

    respond_to do |format|
      if @modern_quote.save
        format.html { redirect_to @modern_quote, notice: 'Modern quote was successfully created.' }
        format.json { render :show, status: :created, location: @modern_quote }
      else
        format.html { render :new }
        format.json { render json: @modern_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modern_quotes/1
  # PATCH/PUT /modern_quotes/1.json
  def update
    respond_to do |format|
      if @modern_quote.update(modern_quote_params)
        format.html { redirect_to @modern_quote, notice: 'Modern quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @modern_quote }
      else
        format.html { render :edit }
        format.json { render json: @modern_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modern_quotes/1
  # DELETE /modern_quotes/1.json
  def destroy
    @modern_quote.destroy
    respond_to do |format|
      format.html { redirect_to modern_quotes_url, notice: 'Modern quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modern_quote
      @modern_quote = ModernQuote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modern_quote_params
      params[:modern_quote]
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_quote, only: [:show, :edit, :update, :destroy]


  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quotes_path, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quotes_path, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:user, :quote, :note, :modern_ref, :biblical_ref)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /home
  def home

  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: 'Static page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params[:static_page]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/modern_quotes_helper.rb
module ModernQuotesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>



<!DOCTYPE html>
<html>
<head>
  <title>Bibref</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="<%= root_path %>">BibRef</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= quotes_path %>">Quotes</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">

          <% if user_signed_in? %>
              <li><a> Signed in as <%= current_user.username %></a></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %> </li>
          <% end %>
        </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
<footer class="footer">
  <div class="container">
    <p class="text-muted">Learn more about this project</p>
  </div>
</footer>
</body>

</html>

app/views/modern_quotes/_form.html.erb
<%= form_for(@modern_quote) do |f| %>
  <% if @modern_quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modern_quote.errors.count, "error") %> prohibited this modern_quote from being saved:</h2>

      <ul>
      <% @modern_quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modern_quotes/edit.html.erb
<h1>Editing Modern Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @modern_quote %> |
<%= link_to 'Back', modern_quotes_path %>

app/views/modern_quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Modern Quotes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modern_quotes.each do |modern_quote| %>
      <tr>
        <td><%= link_to 'Show', modern_quote %></td>
        <td><%= link_to 'Edit', edit_modern_quote_path(modern_quote) %></td>
        <td><%= link_to 'Destroy', modern_quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modern quote', new_modern_quote_path %>

app/views/modern_quotes/new.html.erb
<h1>New Modern Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', modern_quotes_path %>

app/views/modern_quotes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_modern_quote_path(@modern_quote) %> |
<%= link_to 'Back', modern_quotes_path %>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
    <% if @quote.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

          <ul>
            <% @quote.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :user %><br>
      <%= f.text_field :user, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :quote %><br>
      <%= f.text_field :quote, class: 'form-control' %>
    </div>

    <div class="field">
      <div class="row">
        <div class="col-md-4">
          <%= f.label :note %>
          <%= f.text_field :note, class: 'form-control' %>
        </div>

        <div class="col-md-4">
          <%= f.label :modern_ref %>
          <%= f.text_field :modern_ref, class: 'form-control' %>
        </div>

        <div class="col-md-4">
          <%= f.label :biblical_ref %>
          <%= f.text_field :biblical_ref, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="pull-right">
      <div class="actions">
        <%= f.submit class: 'btn btn-classic' %>
      </div>
    </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="pull-right">
  <%= link_to 'New Quote', new_quote_path, class: "btn btn-default btn-sm" %>
</div>
<h1>Quotes</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Quote</th>
      <th>Modern Reference</th>
      <th>Biblical Reference</th>
      <th>User</th>
      <th col width="20%"></th>
    </tr>
    </thead>

    <tbody>
    <% @quotes.each do |quote| %>
        <tr>
          <td><%= link_to "#{quote.quote}", quote %></td>
          <td><%= quote.modern_ref %></td>
          <td><%= quote.biblical_ref %></td>
          <td><%= quote.user %></td>
          <td>
            <%= link_to 'Edit', edit_quote_path(quote), class: "btn btn-primary" %>
            <%= link_to 'Delete', quote, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/quotes/new.html.erb
<div class="pull-right">
  <%= link_to 'Back', quotes_path, class: 'btn btn-default' %>
</div>
<h1>New Quote</h1>

<%= render 'form' %>

app/views/quotes/show.html.erb
<div class="pull-right">
  <%= link_to 'Edit', edit_quote_path(@quote), class: 'btn btn-default' %>
  <%= link_to 'All Quotes', quotes_path, class: 'btn btn-default' %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Submitted by:</strong>
  <%= @quote.user %>

</p>


<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Quote</strong>
      </div>
      <div class="panel-body">
        <p>
          <%= @quote.quote %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong>Biblical Reference</strong>
      </div>
      <div class="panel-body">
        <%= @quote.biblical_ref %>
      </div>
      <div class="panel-heading">
        <strong>Modern Reference</strong>
      </div>
      <div class="panel-body">
        <%= @quote.modern_ref %>
      </div>
    </div>
  </div>
</div>
<div class="col-md-4">
  <strong>Note:</strong>
  <%= @quote.note %>
</div>

app/views/static_pages/_form.html.erb
<%= form_for(@static_page) do |f| %>
  <% if @static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
      <% @static_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/home.html.erb
<h1>This my home page for my really awesome application!</h1>
<h3>More information to come, please be patient</h3>

app/views/static_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>This will be my home page where I will tell you about this awesome project</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @static_pages.each do |static_page| %>
      <tr>
        <td><%= link_to 'Show', static_page %></td>
        <td><%= link_to 'Edit', edit_static_page_path(static_page) %></td>
        <td><%= link_to 'Destroy', static_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--%= link_to 'New Static page', new_static_page_path %-->

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form' %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up here", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>